services:
  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - DEBUG=0
      - DOMAIN_NAME=smtu-tau.onrender.com
    command: >
      sh -c "echo 'Starting server on https://$${DOMAIN_NAME}' && \
             echo 'Checking /frontend_dist contents:' && \
             ls -la /frontend_dist && \
             echo 'Checking /frontend_dist/assets contents:' && \
             ls -la /frontend_dist/assets && \
             python manage.py migrate && \
             python manage.py scan_labs && \
             python manage.py collectstatic --noinput --verbosity 2 && \
             echo 'Checking /app/staticfiles contents after collectstatic:' && \
             ls -la /app/staticfiles && \
             find /app/staticfiles -type f && \
             gunicorn --bind 0.0.0.0:8000 --timeout 120 --workers 4 --log-level debug config.wsgi:application"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge