version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smtu_backend
    ports:
      - "8000:8000"
    # В режиме продакшена обычно не монтируют код в контейнер,
    # потому что всё уже «вшито» на этапе сборки.
    # Поэтому volumes можно убрать или закомментировать:
    # volumes:
    #   - ./Backend:/app
    #   - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - DEBUG=0
      - DOMAIN_NAME=testautomationuniversityplatform2025.ru
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
