version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Backend/Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000/api    # <-- передаём в node-этап
    environment:
      - DJANGO_DEBUG=0
      - DJANGO_SECRET_KEY=paste-your-secret
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
      - VITE_API_BASE_URL=http://localhost:8000/api
    ports:
      - "8000:8000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks: [appnet]
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8000/api/directions/ | grep -q '\"id\"'" ]
      interval: 30s                  # проверка каждые 30 сек
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  appnet:
    driver: bridge
